/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Mar 16 16:39:45 2019. */

#include "mssg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Accel_fields[12] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Accel, a_x, a_x, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Accel, a_y, a_x, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Accel, a_z, a_y, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, Accel, time, a_z, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, Accel, up, time, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, Accel, last_msg, up, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, Accel, number, last_msg, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, Accel, g_x, number, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, Accel, g_y, g_x, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, Accel, g_z, g_y, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, Accel, setting, g_z, 0),
    PB_LAST_FIELD
};

const pb_field_t FinalResult_fields[5] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, FinalResult, up, up, &Accel_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, FinalResult, down, up, &Accel_fields),
    PB_FIELD(  3, INT32   , REPEATED, CALLBACK, OTHER, FinalResult, tens, down, 0),
    PB_FIELD(  4, STRING  , REPEATED, CALLBACK, OTHER, FinalResult, log, tens, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
